config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection do
      post :confirm
    end
  end
  get 'posts/index'
  root 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :favorites
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    validates :comment, presence: true, length: { minimum: 4}
    belongs_to :user
    has_many :favorites, dependent: :destroy
    mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  
    validates :name, presence: true, length: { minimum: 4, maximum: 30 }
    validates :email, presence: true, length: { minimum: 5, maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
    before_validation { email.downcase! }
    has_secure_password
    validates :password, length: { minimum:6 }
    has_many :posts
    has_many :favorites, dependent: :destroy
    mount_uploader :profile_pic, ProfileUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
     before_action :login_required
     
      
    private
    def login_required
        redirect_to new_session_path unless current_user
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def index
        @favorites = current_user.favorites.all
    end
    def create
        favorite = current_user.favorites.create(post_id: params[:post_id])
        redirect_to posts_path, notice: " Le post de #{favorite.post.user.name}  a été ajouté aux favoris"
      end
      def destroy
        favorite = current_user.favorites.find_by(id: params[:id]).destroy
        redirect_to posts_path, notice: "Le post de#{favorite.post.user.name} a été supprimé aux favoris."
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:update, :destroy, :edit, :show]
  def new
    if params[:back]
      @post = Post.new(post_params)
    else
      @post = Post.new
    end
  end

  def index
    @posts= Post.all
  end

  def show
    @favorite = current_user.favorites.find_by(post_id: @post.id)
  end
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if params[:Retour]
      render :new
     else
       if @post.save
         flash[:notice] = "Post posté avec succès" 
         #PostMailer.post_mail(current_user).deliver
         redirect_to posts_path
       else
         render new_post_path
       end
     end
  end

  def confirm
    @post = Post.new(post_params)
    @post.user_id = current_user.id
  end
  
  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = " Post modifié avec succès" 
      redirect_to post_path
    else
      render :edit 
    end
  end

  def destroy
    flash[:danger] = " Post supprime" 
    redirect_to posts_path if @post.destroy
  end

  private
  def post_params
    params.require(:post).permit(:picture, :picture_cache, :comment)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to posts_path(user.id)
    else
      flash.now[:danger] = 'Failed to login'
      render :new
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'Vous avez été déconnecté'
    redirect_to new_session_path
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
     skip_before_action :login_required, only: [:new, :create]
     before_action :set_user, only: [:update, :edit, :show]
     def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to user_path(@user.id)
        else
            render :new
        end
    end

    def edit
    end
  
    def update
      if @user.update(user_params)
        flash[:notice] = " Details utilisateur modifié avec succès" 
        redirect_to user_path
      else
        render :edit 
      end
    end
    private
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile_pic,  :profile_pic_cache)
    end

    def set_user
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def choose_new_or_edit
        if action_name == "new" || action_name == "create"
            confirm_posts_path
            elsif action_name == "edit"
                post_path
               
        end

    end
end

app/helpers/sessions_helper.rb
module SessionsHelper 
    def current_user
        @current_user || @current_user= User.find_by(id: session[:user_id])
    end
    def logged_in?
        current_user.present?
    end
end

app/views/favorites/index.html.erb
<h1>Liste des posts favoris</h1>
<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Published by</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 
  <tbody>
    <% @favorites.each do |fav| %>
      <tr>
        <td><%= fav.post.comment %></td>
        <td><%= fav.post.user.name %></td> 
        <td><%= link_to "Show" , post_path(fav.post.id) %></td>
      </tr>     
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
        <ul>
           <li class="left"><a href="#"><strong> Instagram <em>Clone</em></strong></a></li>
        </ul>
        <ul >
            <% if logged_in? %> 
            <li> <%= link_to "Mes favoris", favorites_path, class: "right" %> </li>
           <li> <%= link_to "Profile", user_path(current_user.id), class: "right" %> </li>
            <li><%= link_to "Logout", session_path(current_user.id), method: :delete , class: "right" %></li>

          <% else%> 

            <%= link_to "Sign up", new_user_path %>
            <%= link_to "Login", new_session_path %>
          <% end%>  
        </ul>
    </header>
      <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class:"#{key}") %>
      <% end %>
  
    <%= yield %>
  </body>
  <footer>
    <div> 
      <ul class="linkfot">
        <li> About</li>
        <li> Blog</li>
        <li> Jobs </li>
        <li> Help </li>
        <li> API </li>
        <li> Privacy </li>
        <li> Terms</li>
        <li>  Top Accounts<li>
        <li> Hashtags </li>
        <li> Locations </li>
        <li> Instagram Lite</li>
      </ul>
     </div>
    <div> </div>
      <p>©Instagram from Facebook</p>
</footer>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true, url:choose_new_or_edit) do |form| %>
    <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2> il y a <%= @post.errors.count %> erreurs</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :"Poster un texte et/ou une image" %>
    <%= form.text_field :comment %> 
    <br>
    </div>

    <%= form.file_field :picture %>
    <%= form.hidden_field :picture_cache %>
        <div class="actions">
        <br>
        <br>
        <%= form.submit class:"btnsbt" %>
        <button> <%= link_to "Liste des posts" , posts_path, class:"buttons" %> </button>
    </div>
            
    
<% end %>

app/views/posts/confirm.html.erb
<h1>COnfirmation du post</h1>
<%= form_with(model: @post, url: posts_path, local: true) do |form| %>
  <!-- Description pour afficher l'image téléchargée -->
  <%= image_tag(@post.picture.url) if @post.picture && @post.picture.url %>
    <%= form.hidden_field :picture %>

  <%= form.hidden_field :picture_cache %>
  <div>
    <%= form.hidden_field :comment %> 
    <br>
    </div>
  <%= form.submit "Poster" %>
<% end %>
<%= form_with(model:@post, url:new_post_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :picture_cache %>
  <%= form.submit "Retour", name: "back" %>
<% end %>

app/views/posts/edit.html.erb
  <h1> Editer un post</h1>
  <%= render 'form' %>

app/views/posts/index.html.erb
<% content_for :head do %>
  <title>List |Facebook- Clone</title>
<% end %>
<h1>Liste des posts</h1>
<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Published by</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.comment %></td>
        <td><%= post.user.name %></td> 
        <td><%= link_to "Show" , post_path(post.id) %></td>
        <%  if current_user==post.user %>
        <td><%= link_to "Edit" , edit_post_path(post.id) %></td>
        <td><%= link_to "Destroy" , post ,method: "delete", data: {confirm: "Etes vous sur de vouloir supprimer?"} %> </td>
        <% end %>
      </tr>     
    <% end %>
  </tbody>
</table>
  <%= link_to 'Ajouter un nouveau post', new_post_path %>

app/views/posts/new.html.erb
  <h1> Ajouter un post</h1>
  <%= render 'form' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Picture:</strong>
  <% if @post.picture && @post.picture.url %>
  <%= image_tag @post.picture.url , height: "300px" %>
  <% end %>
</p>
<% unless @post.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'Supprimer le favori', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'Préféré', favorites_path(post_id: @post.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<%= link_to 'Edit', edit_post_path(@post) %> 
<%= link_to 'Back', posts_path %>

app/views/users/_fuser.html.erb
    <div class="container">
       <div class="side">
 
         <div class="top">
            <%= image_tag "instaic.svg" , class:"instaic", alt:"Instagram-clone icons" %> 
            <h1> Instagram Clone</h1>
        </div> 

            <div class="form">
              <%= form_with(model: @user, local: true) do |fuser| %> 
                 <% if @user.errors.any? %>
                    <div id="error_explanation">
                        <h2> il y a <%= @user.errors.count %> erreurs</h2>
                        <ul>
                            <% @user.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                <% end %>
                <%= fuser.text_field :name, class:"field", placeholder: 'Nom' %> 
                <%= fuser.email_field :email , class:"field", placeholder: 'Adresse e-mail' %>
                <%= fuser.file_field :profile_pic, class:"field"%> 
                <%= fuser.hidden_field :profile_pic_cache, class:"field"%> 
                <%= fuser.password_field :password, class:"field", placeholder: 'Nouveau mot de passe' %>  
                <%= fuser.password_field :password_confirmation, class:"field", placeholder: 'Confirmation de mot de passe' %> 
                <%= fuser.submit class:"btnlog" %>
                <% end %>
                
            </div>
           
        </div>
        
    </div> 

app/views/users/edit.html.erb
<h1><strong> Editer un profile utilisateur</strong></h1>
  <%= render 'fuser' %>

app/views/users/new.html.erb
 <h1><strong> Sign up</strong></h1>
  <%= render 'fuser' %>

app/views/users/show.html.erb
<h1> <strong>Sign in </strong></h1>
<% if @user.profile_pic && @user.profile_pic.url %>
  <%= image_tag @user.profile_pic.url , class: "profilepic" %>
  <% end %>
<p> Name :<%= @user.name %> </p>
<p> Email :<%=@user.email %> </p>
 
<%= link_to "Edit profil ", edit_user_path(@user) %>
 <%= link_to "Liste des posts" , posts_path %> 